### ISSUE TITLE
Convert to typescript

### ISSUE THREAD

**Issue by avneesh0612** [avneesh0612/ChatCube#16]
There a few .jsx files that need to be converted to .tsx. You can see the files [here](https://github.com/avneesh0612/ChatCube/search?l=javascript)

**Comment by sudhir512kj** [comment]
@avneesh0612 I would like to work on this issue.

**Comment by avneesh0612** [comment]
@sudhir512kj Awesome, you can start working! Instructions are given in the readme

**Comment by sudhir512kj** [comment]
@avneesh0612  sure I have started

**Comment by krishguptadev** [comment]
Can I work on this?

**Comment by sudhir512kj** [comment]
I am working on this right now.
Thanks and Regards
Sudhir Meena

**Comment by avneesh0612** [comment]
Hey @sudhir512kj are you still working?

**Comment by avneesh0612** [comment]
I need to unassign you from this issue, since you haven't responded in a long time :)
