### ISSUE TITLE
 Upgrade firebase version from 8 to 9

### ISSUE THREAD

**Issue by avneesh0612** [avneesh0612/ChatCube#17]
The firebase syntax has changed quite a lot in version 8. The documentation - https://firebase.google.com/docs/web/modular-upgrade

**Comment by Anubhab2002** [comment]
Hey can I try working on this issue?

**Comment by Kushagrasaxena-13** [comment]
did you used java for development?

**Comment by aasthagyfg** [comment]
> Hey can I try working on this issue?

Hello @Anubhab2002 sure thing

**Comment by avneesh0612** [comment]
> Hey can I try working on this issue?

Hey @Anubhab2002 sure thing!

**Comment by avneesh0612** [comment]
> did you used java for development?

Hey, no I used javascript.

**Comment by avneesh0612** [comment]
Assigned @Prashoon123
