### ISSUE TITLE
Create color pallete for light and dark mode

### ISSUE THREAD

**Issue by avneesh0612** [avneesh0612/ChatCube#26]
We have the light and dark toggle but the colors aren't changing as we have removed the dark: classes. So you need to add colors for light and dark mode in `tailwind.config.js` and use it on all pages.

**Comment by qwe123coder** [comment]
hey i think i can handle it

**Comment by qwe123coder** [comment]
if you can tell how should i add the themes i can as i am new to tailwind

**Comment by avneesh0612** [comment]
Okay... I will tell you how to

**Comment by avneesh0612** [comment]
Yeah, so you need to add the colors in tailwind.config.js

**Comment by avneesh0612** [comment]
Then you need to change the colors like bg-new-colorname

**Comment by avneesh0612** [comment]
Btw, I like the colors for the dark theme. Can you try a bit more on the sky blue side  for light mode😅

**Comment by qwe123coder** [comment]
> Btw, I like the colors for the dark theme. Can you try a bit more on the sky blue side for light modesweat_smile

cool
